### ISSUE TITLE
Stats Plus does not work on Anki 23.10+

### ISSUE THREAD

**Issue by Exponent4806** [hgiesel/anki_stats_plus#15]
Anki 23.10.1 (fac9e0e) Python 3.11.5 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-6.6.1-arch1-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-11-13 10:11:36

When loading Stats Plus:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/addons.py", line 245, in loadAddons
    __import__(addon.dir_name)
  File "/home/m/.local/share/Anki2/addons21/1009670238/__init__.py", line 1, in <module>
    from .src import init
  File "/home/m/.local/share/Anki2/addons21/1009670238/src/__init__.py", line 5, in <module>
    from .addon_manager import init_addon_manager
  File "/home/m/.local/share/Anki2/addons21/1009670238/src/addon_manager.py", line 7, in <module>
    from ..gui.settings import Settings
  File "/home/m/.local/share/Anki2/addons21/1009670238/gui/settings.py", line 5, in <module>
    from .forms.settings_ui import Ui_Settings
  File "/home/m/.local/share/Anki2/addons21/1009670238/gui/forms/settings_ui.py", line 65, in <module>
    from ..graph_list import GraphList
  File "/home/m/.local/share/Anki2/addons21/1009670238/gui/graph_list.py", line 10, in <module>
    Qt.ItemIsEnabled
AttributeError: type object 'Qt' has no attribute 'ItemIsEnabled'

![image](https://github.com/hgiesel/anki_stats_plus/assets/121114125/2e15efd0-554f-4ec9-b708-166a6a68bdf2)
